config/routes.rb
Rails.application.routes.draw do

  resources :news_items
  devise_for :users
  root 'pages#home'

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  mount_uploader :image, ItemUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController

  def index
    @news_items = NewsItem.all
  end

  def new
    @news_item = NewsItem.new
  end

  def show
    @news_item = NewsItem.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsappCollab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news_items/new.html.erb
<h1>New Item!</h1>

app/views/pages/home.html.erb
<h1>News Home Page</h1>

<%= link_to "Post New Article!", new_news_item_path %>